/* tslint:disable */
/* eslint-disable */
/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DistanceStream } from "./DistanceStream";
import {
  DistanceStreamFromJSON,
  DistanceStreamFromJSONTyped,
  DistanceStreamToJSON,
  DistanceStreamToJSONTyped,
} from "./DistanceStream";
import type { SmoothGradeStream } from "./SmoothGradeStream";
import {
  SmoothGradeStreamFromJSON,
  SmoothGradeStreamFromJSONTyped,
  SmoothGradeStreamToJSON,
  SmoothGradeStreamToJSONTyped,
} from "./SmoothGradeStream";
import type { TemperatureStream } from "./TemperatureStream";
import {
  TemperatureStreamFromJSON,
  TemperatureStreamFromJSONTyped,
  TemperatureStreamToJSON,
  TemperatureStreamToJSONTyped,
} from "./TemperatureStream";
import type { PowerStream } from "./PowerStream";
import {
  PowerStreamFromJSON,
  PowerStreamFromJSONTyped,
  PowerStreamToJSON,
  PowerStreamToJSONTyped,
} from "./PowerStream";
import type { AltitudeStream } from "./AltitudeStream";
import {
  AltitudeStreamFromJSON,
  AltitudeStreamFromJSONTyped,
  AltitudeStreamToJSON,
  AltitudeStreamToJSONTyped,
} from "./AltitudeStream";
import type { CadenceStream } from "./CadenceStream";
import {
  CadenceStreamFromJSON,
  CadenceStreamFromJSONTyped,
  CadenceStreamToJSON,
  CadenceStreamToJSONTyped,
} from "./CadenceStream";
import type { HeartrateStream } from "./HeartrateStream";
import {
  HeartrateStreamFromJSON,
  HeartrateStreamFromJSONTyped,
  HeartrateStreamToJSON,
  HeartrateStreamToJSONTyped,
} from "./HeartrateStream";
import type { TimeStream } from "./TimeStream";
import {
  TimeStreamFromJSON,
  TimeStreamFromJSONTyped,
  TimeStreamToJSON,
  TimeStreamToJSONTyped,
} from "./TimeStream";
import type { SmoothVelocityStream } from "./SmoothVelocityStream";
import {
  SmoothVelocityStreamFromJSON,
  SmoothVelocityStreamFromJSONTyped,
  SmoothVelocityStreamToJSON,
  SmoothVelocityStreamToJSONTyped,
} from "./SmoothVelocityStream";
import type { LatLngStream } from "./LatLngStream";
import {
  LatLngStreamFromJSON,
  LatLngStreamFromJSONTyped,
  LatLngStreamToJSON,
  LatLngStreamToJSONTyped,
} from "./LatLngStream";
import type { MovingStream } from "./MovingStream";
import {
  MovingStreamFromJSON,
  MovingStreamFromJSONTyped,
  MovingStreamToJSON,
  MovingStreamToJSONTyped,
} from "./MovingStream";

/**
 *
 * @export
 * @interface StreamSet
 */
export interface StreamSet {
  /**
   *
   * @type {TimeStream}
   * @memberof StreamSet
   */
  time?: TimeStream;
  /**
   *
   * @type {DistanceStream}
   * @memberof StreamSet
   */
  distance?: DistanceStream;
  /**
   *
   * @type {LatLngStream}
   * @memberof StreamSet
   */
  latlng?: LatLngStream;
  /**
   *
   * @type {AltitudeStream}
   * @memberof StreamSet
   */
  altitude?: AltitudeStream;
  /**
   *
   * @type {SmoothVelocityStream}
   * @memberof StreamSet
   */
  velocitySmooth?: SmoothVelocityStream;
  /**
   *
   * @type {HeartrateStream}
   * @memberof StreamSet
   */
  heartrate?: HeartrateStream;
  /**
   *
   * @type {CadenceStream}
   * @memberof StreamSet
   */
  cadence?: CadenceStream;
  /**
   *
   * @type {PowerStream}
   * @memberof StreamSet
   */
  watts?: PowerStream;
  /**
   *
   * @type {TemperatureStream}
   * @memberof StreamSet
   */
  temp?: TemperatureStream;
  /**
   *
   * @type {MovingStream}
   * @memberof StreamSet
   */
  moving?: MovingStream;
  /**
   *
   * @type {SmoothGradeStream}
   * @memberof StreamSet
   */
  gradeSmooth?: SmoothGradeStream;
}

/**
 * Check if a given object implements the StreamSet interface.
 */
export function instanceOfStreamSet(value: object): value is StreamSet {
  return true;
}

export function StreamSetFromJSON(json: any): StreamSet {
  return StreamSetFromJSONTyped(json, false);
}

export function StreamSetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StreamSet {
  if (json == null) {
    return json;
  }
  return {
    time: json["time"] == null ? undefined : TimeStreamFromJSON(json["time"]),
    distance:
      json["distance"] == null
        ? undefined
        : DistanceStreamFromJSON(json["distance"]),
    latlng:
      json["latlng"] == null ? undefined : LatLngStreamFromJSON(json["latlng"]),
    altitude:
      json["altitude"] == null
        ? undefined
        : AltitudeStreamFromJSON(json["altitude"]),
    velocitySmooth:
      json["velocity_smooth"] == null
        ? undefined
        : SmoothVelocityStreamFromJSON(json["velocity_smooth"]),
    heartrate:
      json["heartrate"] == null
        ? undefined
        : HeartrateStreamFromJSON(json["heartrate"]),
    cadence:
      json["cadence"] == null
        ? undefined
        : CadenceStreamFromJSON(json["cadence"]),
    watts:
      json["watts"] == null ? undefined : PowerStreamFromJSON(json["watts"]),
    temp:
      json["temp"] == null
        ? undefined
        : TemperatureStreamFromJSON(json["temp"]),
    moving:
      json["moving"] == null ? undefined : MovingStreamFromJSON(json["moving"]),
    gradeSmooth:
      json["grade_smooth"] == null
        ? undefined
        : SmoothGradeStreamFromJSON(json["grade_smooth"]),
  };
}

export function StreamSetToJSON(json: any): StreamSet {
  return StreamSetToJSONTyped(json, false);
}

export function StreamSetToJSONTyped(
  value?: StreamSet | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    time: TimeStreamToJSON(value["time"]),
    distance: DistanceStreamToJSON(value["distance"]),
    latlng: LatLngStreamToJSON(value["latlng"]),
    altitude: AltitudeStreamToJSON(value["altitude"]),
    velocity_smooth: SmoothVelocityStreamToJSON(value["velocitySmooth"]),
    heartrate: HeartrateStreamToJSON(value["heartrate"]),
    cadence: CadenceStreamToJSON(value["cadence"]),
    watts: PowerStreamToJSON(value["watts"]),
    temp: TemperatureStreamToJSON(value["temp"]),
    moving: MovingStreamToJSON(value["moving"]),
    grade_smooth: SmoothGradeStreamToJSON(value["gradeSmooth"]),
  };
}
